.TH ARDOUR 1 2023-12-18
.SH NAME
ardour8\-copy-mixer, ardour8\-export, ardour8\-new_empty_session, ardour8\-new_session, ardour8\-lua \- session utilities for the ardour digital audio workstation
.SH SYNOPSIS
ardour8\-copy-mixer
.RB [
.B \-\-help
.RB ]
.RB [
.IR arguments
.RB ]
.br
ardour8\-export
.RB [
.B \-\-help
.RB ]
.RB [
.IR arguments
.RB ]
.br
ardour8\-new_session
.RB [
.B \-\-help
.RB ]
.RB [
.IR arguments
.RB ]
.br
ardour8\-new_empty_session
.RB [
.B \-\-help
.RB ]
.RB [
.IR arguments
.RB ]
.br
ardour8\-new_aaf_session
.RB [
.B \-\-help
.RB ]
.RB [
.IR arguments
.RB ]
.br
ardour8\-lua
.RB [
.B \-\-help
.RB ]
.RB [
.IR arguments
.RB ]
.br
.SH DESCRIPTION
\fBardour8\-copy-mixer\fP copies mixer-settings from one session to another.
.br
\fBardour8\-export\fP exports an ardour session from the commandline.
.br
\fBardour8\-new_session\fP creates a new session from the commandline.
.br
\fBardour8\-new_empty_session\fP creates a new empty session from the commandline.
.br
\fBardour8-new_aaf_session\fP creates a new session based on an AAF file from the commandline.
.br
\fBardour8\-lua\fP interactive Ardour Lua interpreter.
.SH OPTIONS
.TP
.B \-\-help
Display detailed usage information.
.SH "AUTHORS"
.PP
This manual page was written by IOhannes m zmölnig
<zmoelnig@iem.at>
for the
Debian
system (but may be used by others).
Permission is granted to copy, distribute and/or modify this document under the
terms of the
GNU General Public License, Version 2 or any later version
published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common\-licenses/GPL.
